<!doctype html><html lang=en dir=auto><head><meta charset=utf-8><meta http-equiv=x-ua-compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name=robots content="index, follow"><title>Java异常 | luolin1024</title><meta name=keywords content="Java/Java基础"><meta name=description content="Throwable throw new Exception()既代表 java 运行进入了一个新的分支，不再执行new Exception()后面的语句了，之后再来执行finally中的"><meta name=author content="luolin"><link rel=canonical href=https://luolin1024.github.io/blog_prepublish/%E6%8A%80%E6%9C%AF%E6%8F%90%E5%8D%87/java/java%E5%BC%82%E5%B8%B8/><script defer src=https://blogcounter.luolin.us.kg/script.js data-website-id=c8850e2c-16aa-465e-aa6f-5392c9397317></script>
<script src=/js/umami-stats.js></script>
<script src=https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js></script>
<link rel=stylesheet href=https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css><script src=https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js></script>
<link crossorigin=anonymous href=/assets/css/stylesheet.css rel="preload stylesheet" as=style><link rel=icon href=https://luolin1024.github.io/favicon.ico><link rel=icon type=image/png sizes=16x16 href=https://luolin1024.github.io/favicon-16x16.png><link rel=icon type=image/png sizes=32x32 href=https://luolin1024.github.io/favicon-32x32.png><link rel=apple-touch-icon href=https://luolin1024.github.io/apple-touch-icon.png><link rel=mask-icon href=https://luolin1024.github.io/favicon.ico><meta name=theme-color content="#2e2e33"><meta name=msapplication-TileColor content="#2e2e33"><noscript><style>#theme-toggle,.top-link{display:none}</style><style>@media(prefers-color-scheme:dark){:root{--theme:rgb(29, 30, 32);--entry:rgb(46, 46, 51);--primary:rgb(218, 218, 219);--secondary:rgb(155, 156, 157);--tertiary:rgb(65, 66, 68);--content:rgb(196, 196, 197);--code-block-bg:rgb(46, 46, 51);--code-bg:rgb(55, 56, 62);--border:rgb(51, 51, 51)}.list{background:var(--theme)}.list:not(.dark)::-webkit-scrollbar-track{background:0 0}.list:not(.dark)::-webkit-scrollbar-thumb{border-color:var(--theme)}}</style></noscript><html><head><link rel=stylesheet href=https://cdn.jsdelivr.net/npm/jetbrains-mono@1.0.6/css/jetbrains-mono.min.css><link rel=stylesheet href=https://cdn.jsdelivr.net/npm/lxgw-wenkai-lite-webfont@1.1.0/style.css><link rel=stylesheet href=https://cdn.staticfile.org/lxgw-wenkai-screen-webfont/1.6.0/style.css><style>body{font-family:lxgw wenkai lite,sans-serif;font-family:lxgw wenkai screen,sans-serif}</style></head></html><meta property="og:title" content="Java异常"><meta property="og:description" content="Throwable throw new Exception()既代表 java 运行进入了一个新的分支，不再执行new Exception()后面的语句了，之后再来执行finally中的"><meta property="og:type" content="article"><meta property="og:url" content="https://luolin1024.github.io/blog_prepublish/%E6%8A%80%E6%9C%AF%E6%8F%90%E5%8D%87/java/java%E5%BC%82%E5%B8%B8/"><meta property="article:section" content="blog_prepublish"><meta property="article:published_time" content="2023-02-11T00:32:19+08:00"><meta property="article:modified_time" content="2024-03-21T00:55:57+08:00"><meta property="og:site_name" content="luolin的博客"><meta name=twitter:card content="summary"><meta name=twitter:title content="Java异常"><meta name=twitter:description content="Throwable throw new Exception()既代表 java 运行进入了一个新的分支，不再执行new Exception()后面的语句了，之后再来执行finally中的"><script type=application/ld+json>{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Blog_prepublishes","item":"https://luolin1024.github.io/blog_prepublish/"},{"@type":"ListItem","position":2,"name":"Java异常","item":"https://luolin1024.github.io/blog_prepublish/%E6%8A%80%E6%9C%AF%E6%8F%90%E5%8D%87/java/java%E5%BC%82%E5%B8%B8/"}]}</script><script type=application/ld+json>{"@context":"https://schema.org","@type":"BlogPosting","headline":"Java异常","name":"Java异常","description":"Throwable throw new Exception()既代表 java 运行进入了一个新的分支，不再执行new Exception()后面的语句了，之后再来执行finally中的","keywords":["Java/Java基础"],"articleBody":"Throwable throw new Exception()既代表 java 运行进入了一个新的分支，不再执行new Exception()后面的语句了，之后再来执行finally中的内容。\njava将所有的错误封装为一个对象，其根本父类为 Throwable, Throwable 有两个子类：Error 和 Exception。\nError Error一般为底层的不可恢复的类； Error 是 Throwable 的子类，用于指示合理的应用程序不应该试图捕获的严重问题。大多数这样的错误都是异常条件。虽然 ThreadDeath 错误是一个“正规”的条件，但它也是 Error 的子类，因为大多数应用程序都不应该试图捕获它。在执行该方法期间，无需在其 throws 子句中声明可能抛出但是未能捕获的 Error 的任何子类，因为这些错误可能是再也不会发生的异常条件。 Exception Exception 类及其子类是 Throwable 的一种形式，它指出了合理的应用程序想要捕获的条件。 Exception：分为未检查异常(RuntimeException)和已检查异常(非RuntimeException)。未检查异常是因为程序员没有进行必需要的检查，因为疏忽和错误而引起的错误。 RuntimeException（运行时异常、既unchecked，未检查异常）是那些可能在 Java 虚拟机正常运行期间抛出的异常的超类。可能在执行方法期间抛出但未被捕获的, RuntimeException 的任何子类都无需在 throws 子句中进行声明。它是Exception 的子类。 几个经典的RunTimeException： java.lang.NullPointerException; java.lang.ArithmaticException; java.lang.ArrayIndexoutofBoundsException； Runtime Exception 和 Exception Runtime Exception：在定义方法时不需要声明会抛出runtime exception； 在调用这个方法时不需要捕获这个runtime exception； runtime exception是从java.lang.RuntimeException或java.lang.Error类衍生出来的。 例如：nullpointexception，IndexOutOfBoundsException就属于runtime exception Exception:定义方法时必须声明所有可能会抛出的exception； 在调用这个方法时，必须捕获它的checked exception，不然就得把它的exception传递下去；exception是从java.lang.Exception类衍生出来的。例如：IOException，SQLException就属于Exception。Exception 属于应用程序级别的异常，这类异常必须捕捉,Exception体系包括RuntimeException体系和其他非RuntimeException的体系RuntimeException 表示系统异常，比较严重，如果出现RuntimeException，那么一定是程序员的错误 异常处理机制 在java中，异常有两种处理机制：\ntry-catch-finally throw 上面说的异常处理的两种方式是有区别的，第一种遇到异常后在catch中直接处理掉，处理完成后继续执行try-catch代码块后面的代码，而throw则是抛给上一层处理（可以一直向上抛，直到在）。\n一个简单的例子：\n@Test public void test1(){ int i = 10 / 0; System.out.println(\"程序除0了...\"); /** * 打印结果： * java.lang.ArithmeticException: / by zero * * at com.exception.ExceptionTest.test2(ExceptionTest.java:32) */ } 在这个例子中我是直接尝试让程序除0，然后此时就会直接抛出ArithmeticException，后面的打印代码也是直接不再执行的，这样就影响了程序的正常运行。\n异常处理机制一：try-catch-finally（捕获异常） 其实不管是哪一种Exception，在我们知道会发生异常的时候，最终的解决方案都是try-catch-finally,throw到最后还是要通过try-catch-finally来解决的。我们对上面的例子进行改良：\n@Test public void test2(){ try { int i = 10 / 0; System.out.println(\"程序除0了...\"); }catch (Exception e){ System.out.println(\"catch到了异常...\"); }finally { System.out.println(\"finally中的代码...\"); } System.out.println(\"try-catch-finally之后的代码...\"); /** * 打印结果： * catch到了异常... * finally中的代码... * try-catch-finally之后的代码... */ } 此时我们就看到，在发生异常的时候，我们可以在catch中解决好碰到的异常，然后代码块后面的代码跟着正常执行。\n异常处理机制二：throws(声明异常) 在上面的try-catch机制中我们可以看成自身感冒了，然后自己去药店买了点药，吃完后就好了，不会有什么影响；而throw就类似生病了，自身吃药治不好(既当前方法不处理)，这个时候我们就需要到医院跟医生交代我们有什么问题，然后让医生来解决，可能当前医生治不好，那么这个医生是可以接着throw到上一级的。\n@Test public void test4() throws FileNotFoundException { new FileInputStream(new File(\"dd\")); System.out.println(\"---------\"); /** * 打印结果： * java.io.FileNotFoundException: dd (系统找不到指定的文件。) * * at java.io.FileInputStream.open0(Native Method) */ } 直接爆红出异常，而且后面的打印语句是没有执行的。说明throw这种方式也会影响程序的正常执行，所有我们需要在调用test4()的地方try-catch处理。\n手动抛异常 在这里介绍手动抛RuntimeException和Exception：\npublic class MyClass{ public MyClass() throws RuntimeException{ throw new RuntimeException(); } public MyClass(String msg) throws Exception { throw new Exception(msg); } } 然后我们调用这两个构造器的时候的处理方式如下：\n@Test public void test5(){ new MyClass(); /** * 打印结果： * java.lang.RuntimeException * at com.exception.MyClass.(MyClass.java:15) */ } @Test public void test6(){ try { new MyClass(\"测试untracked Exception\"); } catch (Exception e) { System.out.println(\"捕获到了异常\"); } System.out.println(\"执行完了try-catch\"); /** * 打印结果： * 捕获到了异常 * 执行完了try-catch */ } 自定义异常 自定义异常必须继承自Exception或者Exception的子类，一个简单的自定义异常如下：\npublic class MyException extends Exception { public MyException(){ super(); } public MyException(String msg){ super(msg); } } 抛的方式如下：\npublic MyClass(String msg) throws MyException { throw new MyException(msg); } 异常中的子父类 在java中，若碰到异常的时候采用try-catch方式捕获异常，如果第一个catch捕获的异常必须和后面捕获的异常同级或者是后面捕获的异常的子类。 在代码中throw出去的异常一定得是方法上throws出去的异常的子类。 ","wordCount":"2587","inLanguage":"en","datePublished":"2023-02-11T00:32:19+08:00","dateModified":"2024-03-21T00:55:57+08:00","author":{"@type":"Person","name":"luolin"},"mainEntityOfPage":{"@type":"WebPage","@id":"https://luolin1024.github.io/blog_prepublish/%E6%8A%80%E6%9C%AF%E6%8F%90%E5%8D%87/java/java%E5%BC%82%E5%B8%B8/"},"publisher":{"@type":"Organization","name":"luolin1024","logo":{"@type":"ImageObject","url":"https://luolin1024.github.io/favicon.ico"}}}</script></head><body id=top><script>window.matchMedia("(prefers-color-scheme: dark)").matches&&document.body.classList.add("dark")</script><header class=header><nav class=nav><div class=logo><a href=https://luolin1024.github.io accesskey=h title="luolin的博客 (Alt + H)">luolin的博客</a><div class=logo-switches></div></div><ul id=menu><li><a href=https://luolin1024.github.io/posts title=📚文章><span>📚文章</span></a></li><li><a href=https://luolin1024.github.io/archives/ title=⏱时间轴><span>⏱时间轴</span></a></li><li><a href=https://luolin1024.github.io/search/ title="🔍搜索 (Alt + /)" accesskey=/><span>🔍搜索</span></a></li><li><a href=https://luolin1024.github.io/tags title=🔖标签><span>🔖标签</span></a></li><li><a href=https://luolin1024.github.io/about title=🙋🏻‍♂️关于><span>🙋🏻‍♂️关于</span></a></li><li><a href=https://luolin1024.github.io/links title=🤝友链><span>🤝友链</span></a></li></ul></nav></header><main class=main><article class=post-single><header class=post-header><div class=breadcrumbs><a href=https://luolin1024.github.io>Home</a>&nbsp;»&nbsp;<a href=https://luolin1024.github.io/blog_prepublish/>Blog_prepublishes</a></div><h1 class="post-title entry-hint-parent">Java异常</h1><div class=post-meta><span title='2023-02-11 00:32:19 +0800 +0800'>2023-02-11</span>&nbsp;·&nbsp;6 min&nbsp;·&nbsp;2587 words&nbsp;·&nbsp;luolin
本文总阅读量 <span id=umami_value_page_pv></span> 次
本文总访客量 <span id=umami_value_page_uv></span> 人</div></header><aside id=toc-container class="toc-container wide"><div class=toc><details open><summary accesskey=c title="(Alt + C)"><span class=details>Table of Contents</span></summary><div class=inner><ul><li><a href=#throwable aria-label=Throwable>Throwable</a><ul><li><a href=#error aria-label=Error>Error</a></li><li><a href=#exception aria-label=Exception>Exception</a></li><li><a href=#runtime-exception-%e5%92%8c-exception aria-label="Runtime Exception 和 Exception">Runtime Exception 和 Exception</a></li></ul></li><li><a href=#%e5%bc%82%e5%b8%b8%e5%a4%84%e7%90%86%e6%9c%ba%e5%88%b6 aria-label=异常处理机制>异常处理机制</a><ul><li><a href=#%e5%bc%82%e5%b8%b8%e5%a4%84%e7%90%86%e6%9c%ba%e5%88%b6%e4%b8%80try-catch-finally%e6%8d%95%e8%8e%b7%e5%bc%82%e5%b8%b8 aria-label=异常处理机制一：try-catch-finally（捕获异常）>异常处理机制一：try-catch-finally（捕获异常）</a></li><li><a href=#%e5%bc%82%e5%b8%b8%e5%a4%84%e7%90%86%e6%9c%ba%e5%88%b6%e4%ba%8cthrows%e5%a3%b0%e6%98%8e%e5%bc%82%e5%b8%b8 aria-label=异常处理机制二：throws(声明异常)>异常处理机制二：throws(声明异常)</a></li></ul></li><li><a href=#%e6%89%8b%e5%8a%a8%e6%8a%9b%e5%bc%82%e5%b8%b8 aria-label=手动抛异常>手动抛异常</a></li><li><a href=#%e8%87%aa%e5%ae%9a%e4%b9%89%e5%bc%82%e5%b8%b8 aria-label=自定义异常>自定义异常</a></li><li><a href=#%e5%bc%82%e5%b8%b8%e4%b8%ad%e7%9a%84%e5%ad%90%e7%88%b6%e7%b1%bb aria-label=异常中的子父类>异常中的子父类</a></li></ul></div></details></div></aside><script>let activeElement,elements;window.addEventListener("DOMContentLoaded",function(){checkTocPosition(),elements=document.querySelectorAll("h1[id],h2[id],h3[id],h4[id],h5[id],h6[id]"),activeElement=elements[0];const t=encodeURI(activeElement.getAttribute("id")).toLowerCase();document.querySelector(`.inner ul li a[href="#${t}"]`).classList.add("active")},!1),window.addEventListener("resize",function(){checkTocPosition()},!1),window.addEventListener("scroll",()=>{activeElement=Array.from(elements).find(e=>{if(getOffsetTop(e)-window.pageYOffset>0&&getOffsetTop(e)-window.pageYOffset<window.innerHeight/2)return e})||activeElement,elements.forEach(e=>{const t=encodeURI(e.getAttribute("id")).toLowerCase();e===activeElement?document.querySelector(`.inner ul li a[href="#${t}"]`).classList.add("active"):document.querySelector(`.inner ul li a[href="#${t}"]`).classList.remove("active")})},!1);const main=parseInt(getComputedStyle(document.body).getPropertyValue("--article-width"),10),toc=parseInt(getComputedStyle(document.body).getPropertyValue("--toc-width"),10),gap=parseInt(getComputedStyle(document.body).getPropertyValue("--gap"),10);function checkTocPosition(){const e=document.body.scrollWidth;e-main-toc*2-gap*4>0?document.getElementById("toc-container").classList.add("wide"):document.getElementById("toc-container").classList.remove("wide")}function getOffsetTop(e){if(!e.getClientRects().length)return 0;let t=e.getBoundingClientRect(),n=e.ownerDocument.defaultView;return t.top+n.pageYOffset}</script><div class=post-content><h3 id=throwable>Throwable<a hidden class=anchor aria-hidden=true href=#throwable>#</a></h3><p><code>throw new Exception()</code>既代表 java 运行进入了一个新的分支，不再执行<code>new Exception()</code>后面的语句了，之后再来执行finally中的内容。</p><p><div class=post-img-view><a data-fancybox=gallery href=https://cdn.jsdelivr.net/gh/luolin1024/image@main/img/1596506179351-665acf26-0743-4c22-8a17-a0b98ecb5c0f.jpeg><img src=https://cdn.jsdelivr.net/gh/luolin1024/image@main/img/1596506179351-665acf26-0743-4c22-8a17-a0b98ecb5c0f.jpeg alt=Exception.jpg></a></div>java将所有的错误封装为一个对象，其根本父类为 Throwable, Throwable 有两个子类：Error 和 Exception。</p><h4 id=error>Error<a hidden class=anchor aria-hidden=true href=#error>#</a></h4><ol><li>Error一般为底层的不可恢复的类；</li><li>Error 是 Throwable 的子类，用于指示合理的应用程序不应该试图捕获的严重问题。大多数这样的错误都是异常条件。虽然 ThreadDeath 错误是一个“正规”的条件，但它也是 Error 的子类，因为大多数应用程序都不应该试图捕获它。在执行该方法期间，无需在其 throws 子句中声明可能抛出但是未能捕获的 Error 的任何子类，因为这些错误可能是再也不会发生的异常条件。</li></ol><h4 id=exception>Exception<a hidden class=anchor aria-hidden=true href=#exception>#</a></h4><ol><li>Exception 类及其子类是 Throwable 的一种形式，它指出了合理的应用程序想要捕获的条件。</li><li>Exception：分为未检查异常(RuntimeException)和已检查异常(非RuntimeException)。未检查异常是因为程序员没有进行必需要的检查，因为疏忽和错误而引起的错误。</li><li>RuntimeException（运行时异常、既unchecked，未检查异常）是那些可能在 Java 虚拟机正常运行期间抛出的异常的超类。可能在执行方法期间抛出但未被捕获的, RuntimeException 的任何子类都无需在 throws 子句中进行声明。它是Exception 的子类。</li><li>几个经典的RunTimeException：<ol><li>java.lang.NullPointerException;</li><li>java.lang.ArithmaticException;</li><li>java.lang.ArrayIndexoutofBoundsException；</li></ol></li></ol><h4 id=runtime-exception-和-exception>Runtime Exception 和 Exception<a hidden class=anchor aria-hidden=true href=#runtime-exception-和-exception>#</a></h4><ol><li>Runtime Exception：在定义方法时不需要声明会抛出runtime exception； 在调用这个方法时不需要捕获这个runtime exception； runtime exception是从java.lang.RuntimeException或java.lang.Error类衍生出来的。 例如：nullpointexception，IndexOutOfBoundsException就属于runtime exception</li><li>Exception:定义方法时必须声明所有可能会抛出的exception； 在调用这个方法时，必须捕获它的checked exception，不然就得把它的exception传递下去；exception是从java.lang.Exception类衍生出来的。例如：IOException，SQLException就属于Exception。Exception 属于应用程序级别的异常，这类异常必须捕捉,Exception体系包括RuntimeException体系和其他非RuntimeException的体系RuntimeException 表示系统异常，比较严重，如果出现RuntimeException，那么一定是程序员的错误</li></ol><h3 id=异常处理机制>异常处理机制<a hidden class=anchor aria-hidden=true href=#异常处理机制>#</a></h3><p>在java中，异常有两种处理机制：</p><ol><li>try-catch-finally</li><li>throw</li></ol><p>上面说的异常处理的两种方式是有区别的，第一种遇到异常后在catch中直接处理掉，处理完成后继续执行try-catch代码块后面的代码，而throw则是抛给上一层处理（可以一直向上抛，直到在）。</p><p>一个简单的例子：</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=nd>@Test</span>
</span></span><span class=line><span class=cl><span class=kd>public</span> <span class=kt>void</span> <span class=nf>test1</span><span class=o>(){</span>
</span></span><span class=line><span class=cl>    <span class=kt>int</span> <span class=n>i</span> <span class=o>=</span> <span class=mi>10</span> <span class=o>/</span> <span class=mi>0</span><span class=o>;</span>
</span></span><span class=line><span class=cl>    <span class=n>System</span><span class=o>.</span><span class=na>out</span><span class=o>.</span><span class=na>println</span><span class=o>(</span><span class=s>&#34;程序除0了...&#34;</span><span class=o>);</span>
</span></span><span class=line><span class=cl>    <span class=cm>/**
</span></span></span><span class=line><span class=cl><span class=cm>     * 打印结果：
</span></span></span><span class=line><span class=cl><span class=cm>     * java.lang.ArithmeticException: / by zero
</span></span></span><span class=line><span class=cl><span class=cm>     *
</span></span></span><span class=line><span class=cl><span class=cm>     * 	at com.exception.ExceptionTest.test2(ExceptionTest.java:32)
</span></span></span><span class=line><span class=cl><span class=cm>     */</span>
</span></span><span class=line><span class=cl><span class=o>}</span>
</span></span></code></pre></div><p>在这个例子中我是直接尝试让程序除0，然后此时就会直接抛出<code>ArithmeticException</code>，后面的打印代码也是直接不再执行的，这样就影响了程序的正常运行。</p><h4 id=异常处理机制一try-catch-finally捕获异常>异常处理机制一：try-catch-finally（捕获异常）<a hidden class=anchor aria-hidden=true href=#异常处理机制一try-catch-finally捕获异常>#</a></h4><p>其实不管是哪一种Exception，在我们知道会发生异常的时候，最终的解决方案都是<code>try-catch-finally</code>,throw到最后还是要通过<code>try-catch-finally</code>来解决的。我们对上面的例子进行改良：</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=nd>@Test</span>
</span></span><span class=line><span class=cl><span class=kd>public</span> <span class=kt>void</span> <span class=nf>test2</span><span class=o>(){</span>
</span></span><span class=line><span class=cl>    <span class=k>try</span> <span class=o>{</span>
</span></span><span class=line><span class=cl>        <span class=kt>int</span> <span class=n>i</span> <span class=o>=</span> <span class=mi>10</span> <span class=o>/</span> <span class=mi>0</span><span class=o>;</span>
</span></span><span class=line><span class=cl>        <span class=n>System</span><span class=o>.</span><span class=na>out</span><span class=o>.</span><span class=na>println</span><span class=o>(</span><span class=s>&#34;程序除0了...&#34;</span><span class=o>);</span>
</span></span><span class=line><span class=cl>    <span class=o>}</span><span class=k>catch</span> <span class=o>(</span><span class=n>Exception</span> <span class=n>e</span><span class=o>){</span>
</span></span><span class=line><span class=cl>        <span class=n>System</span><span class=o>.</span><span class=na>out</span><span class=o>.</span><span class=na>println</span><span class=o>(</span><span class=s>&#34;catch到了异常...&#34;</span><span class=o>);</span>
</span></span><span class=line><span class=cl>    <span class=o>}</span><span class=k>finally</span> <span class=o>{</span>
</span></span><span class=line><span class=cl>        <span class=n>System</span><span class=o>.</span><span class=na>out</span><span class=o>.</span><span class=na>println</span><span class=o>(</span><span class=s>&#34;finally中的代码...&#34;</span><span class=o>);</span>
</span></span><span class=line><span class=cl>    <span class=o>}</span>
</span></span><span class=line><span class=cl>    <span class=n>System</span><span class=o>.</span><span class=na>out</span><span class=o>.</span><span class=na>println</span><span class=o>(</span><span class=s>&#34;try-catch-finally之后的代码...&#34;</span><span class=o>);</span>
</span></span><span class=line><span class=cl>    <span class=cm>/**
</span></span></span><span class=line><span class=cl><span class=cm>     * 打印结果：
</span></span></span><span class=line><span class=cl><span class=cm>     * catch到了异常...
</span></span></span><span class=line><span class=cl><span class=cm>     * finally中的代码...
</span></span></span><span class=line><span class=cl><span class=cm>     * try-catch-finally之后的代码...
</span></span></span><span class=line><span class=cl><span class=cm>     */</span>
</span></span><span class=line><span class=cl><span class=o>}</span>
</span></span></code></pre></div><p>此时我们就看到，在发生异常的时候，我们可以在catch中解决好碰到的异常，然后代码块后面的代码跟着正常执行。</p><h4 id=异常处理机制二throws声明异常>异常处理机制二：throws(声明异常)<a hidden class=anchor aria-hidden=true href=#异常处理机制二throws声明异常>#</a></h4><p>在上面的<code>try-catch</code>机制中我们可以看成自身感冒了，然后自己去药店买了点药，吃完后就好了，不会有什么影响；而throw就类似生病了，自身吃药治不好(既当前方法不处理)，这个时候我们就需要到医院跟医生交代我们有什么问题，然后让医生来解决，可能当前医生治不好，那么这个医生是可以接着<code>throw</code>到上一级的。</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=nd>@Test</span>
</span></span><span class=line><span class=cl><span class=kd>public</span> <span class=kt>void</span> <span class=nf>test4</span><span class=o>()</span> <span class=kd>throws</span> <span class=n>FileNotFoundException</span> <span class=o>{</span>
</span></span><span class=line><span class=cl>    <span class=k>new</span> <span class=n>FileInputStream</span><span class=o>(</span><span class=k>new</span> <span class=n>File</span><span class=o>(</span><span class=s>&#34;dd&#34;</span><span class=o>));</span>
</span></span><span class=line><span class=cl>    <span class=n>System</span><span class=o>.</span><span class=na>out</span><span class=o>.</span><span class=na>println</span><span class=o>(</span><span class=s>&#34;---------&#34;</span><span class=o>);</span>
</span></span><span class=line><span class=cl>    <span class=cm>/**
</span></span></span><span class=line><span class=cl><span class=cm>     * 打印结果：
</span></span></span><span class=line><span class=cl><span class=cm>     * java.io.FileNotFoundException: dd (系统找不到指定的文件。)
</span></span></span><span class=line><span class=cl><span class=cm>     *
</span></span></span><span class=line><span class=cl><span class=cm>     * 	at java.io.FileInputStream.open0(Native Method)
</span></span></span><span class=line><span class=cl><span class=cm>     */</span>
</span></span><span class=line><span class=cl><span class=o>}</span>
</span></span></code></pre></div><p>直接爆红出异常，而且后面的打印语句是没有执行的。说明throw这种方式也会影响程序的正常执行，所有我们需要在调用test4()的地方<code>try-catch</code>处理。</p><h3 id=手动抛异常>手动抛异常<a hidden class=anchor aria-hidden=true href=#手动抛异常>#</a></h3><p>在这里介绍手动抛RuntimeException和Exception：</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=kd>public</span> <span class=kd>class</span> <span class=nc>MyClass</span><span class=o>{</span>
</span></span><span class=line><span class=cl>    <span class=kd>public</span> <span class=nf>MyClass</span><span class=o>()</span> <span class=kd>throws</span> <span class=n>RuntimeException</span><span class=o>{</span>
</span></span><span class=line><span class=cl>        <span class=k>throw</span>  <span class=k>new</span> <span class=n>RuntimeException</span><span class=o>();</span>
</span></span><span class=line><span class=cl>    <span class=o>}</span>
</span></span><span class=line><span class=cl>    <span class=kd>public</span> <span class=nf>MyClass</span><span class=o>(</span><span class=n>String</span> <span class=n>msg</span><span class=o>)</span> <span class=kd>throws</span> <span class=n>Exception</span> <span class=o>{</span>
</span></span><span class=line><span class=cl>        <span class=k>throw</span> <span class=k>new</span> <span class=n>Exception</span><span class=o>(</span><span class=n>msg</span><span class=o>);</span>
</span></span><span class=line><span class=cl>    <span class=o>}</span>
</span></span><span class=line><span class=cl><span class=o>}</span>
</span></span></code></pre></div><p>然后我们调用这两个构造器的时候的处理方式如下：</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=nd>@Test</span>
</span></span><span class=line><span class=cl><span class=kd>public</span> <span class=kt>void</span> <span class=nf>test5</span><span class=o>(){</span>
</span></span><span class=line><span class=cl>    <span class=k>new</span> <span class=n>MyClass</span><span class=o>();</span>
</span></span><span class=line><span class=cl>    <span class=cm>/**
</span></span></span><span class=line><span class=cl><span class=cm>     * 打印结果：
</span></span></span><span class=line><span class=cl><span class=cm>     * java.lang.RuntimeException
</span></span></span><span class=line><span class=cl><span class=cm>     * 	at com.exception.MyClass.&lt;init&gt;(MyClass.java:15)
</span></span></span><span class=line><span class=cl><span class=cm>     */</span>
</span></span><span class=line><span class=cl><span class=o>}</span>
</span></span><span class=line><span class=cl><span class=nd>@Test</span>
</span></span><span class=line><span class=cl><span class=kd>public</span> <span class=kt>void</span> <span class=nf>test6</span><span class=o>(){</span>
</span></span><span class=line><span class=cl>    <span class=k>try</span> <span class=o>{</span>
</span></span><span class=line><span class=cl>        <span class=k>new</span> <span class=n>MyClass</span><span class=o>(</span><span class=s>&#34;测试untracked Exception&#34;</span><span class=o>);</span>
</span></span><span class=line><span class=cl>    <span class=o>}</span> <span class=k>catch</span> <span class=o>(</span><span class=n>Exception</span> <span class=n>e</span><span class=o>)</span> <span class=o>{</span>
</span></span><span class=line><span class=cl>        <span class=n>System</span><span class=o>.</span><span class=na>out</span><span class=o>.</span><span class=na>println</span><span class=o>(</span><span class=s>&#34;捕获到了异常&#34;</span><span class=o>);</span>
</span></span><span class=line><span class=cl>    <span class=o>}</span>
</span></span><span class=line><span class=cl>    <span class=n>System</span><span class=o>.</span><span class=na>out</span><span class=o>.</span><span class=na>println</span><span class=o>(</span><span class=s>&#34;执行完了try-catch&#34;</span><span class=o>);</span>
</span></span><span class=line><span class=cl>    <span class=cm>/**
</span></span></span><span class=line><span class=cl><span class=cm>     * 打印结果：
</span></span></span><span class=line><span class=cl><span class=cm>     * 捕获到了异常
</span></span></span><span class=line><span class=cl><span class=cm>     * 执行完了try-catch
</span></span></span><span class=line><span class=cl><span class=cm>     */</span>
</span></span><span class=line><span class=cl><span class=o>}</span>
</span></span></code></pre></div><h3 id=自定义异常>自定义异常<a hidden class=anchor aria-hidden=true href=#自定义异常>#</a></h3><p>自定义异常必须继承自Exception或者Exception的子类，一个简单的自定义异常如下：</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=kd>public</span> <span class=kd>class</span> <span class=nc>MyException</span> <span class=kd>extends</span> <span class=n>Exception</span> <span class=o>{</span>
</span></span><span class=line><span class=cl>    <span class=kd>public</span> <span class=nf>MyException</span><span class=o>(){</span>
</span></span><span class=line><span class=cl>        <span class=kd>super</span><span class=o>();</span>
</span></span><span class=line><span class=cl>    <span class=o>}</span>
</span></span><span class=line><span class=cl>    <span class=kd>public</span> <span class=nf>MyException</span><span class=o>(</span><span class=n>String</span> <span class=n>msg</span><span class=o>){</span>
</span></span><span class=line><span class=cl>        <span class=kd>super</span><span class=o>(</span><span class=n>msg</span><span class=o>);</span>
</span></span><span class=line><span class=cl>    <span class=o>}</span>
</span></span><span class=line><span class=cl><span class=o>}</span>
</span></span></code></pre></div><p>抛的方式如下：</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=kd>public</span> <span class=nf>MyClass</span><span class=o>(</span><span class=n>String</span> <span class=n>msg</span><span class=o>)</span> <span class=kd>throws</span> <span class=n>MyException</span> <span class=o>{</span>
</span></span><span class=line><span class=cl>    <span class=k>throw</span> <span class=k>new</span> <span class=n>MyException</span><span class=o>(</span><span class=n>msg</span><span class=o>);</span>
</span></span><span class=line><span class=cl><span class=o>}</span>
</span></span></code></pre></div><h3 id=异常中的子父类>异常中的子父类<a hidden class=anchor aria-hidden=true href=#异常中的子父类>#</a></h3><ol><li>在java中，若碰到异常的时候采用try-catch方式捕获异常，如果第一个catch捕获的异常必须和后面捕获的异常同级或者是后面捕获的异常的子类。</li><li>在代码中throw出去的异常一定得是方法上throws出去的异常的子类。</li></ol></div><footer class=post-footer><ul class=post-tags><li><a href=https://luolin1024.github.io/tags/java/java%E5%9F%BA%E7%A1%80/>Java/Java基础</a></li></ul><nav class=paginav><a class=prev href=https://luolin1024.github.io/blog_prepublish/%E6%8A%80%E6%9C%AF%E6%8F%90%E5%8D%87/java/java%E5%8F%AF%E5%8F%98%E5%8F%82%E6%95%B0/><span class=title>« Prev</span><br><span>Java可变参数</span></a>
<a class=next href=https://luolin1024.github.io/blog_prepublish/%E6%8A%80%E6%9C%AF%E6%8F%90%E5%8D%87/java/java%E6%8E%92%E5%BA%8F/><span class=title>Next »</span><br><span>Java排序</span></a></nav><div class=related-posts><h2>相关文章</h2><ul><li>· <a href=/blog_prepublish/%E6%8A%80%E6%9C%AF%E6%8F%90%E5%8D%87/java/java%E7%BA%BF%E7%A8%8B%E6%B1%A0%E7%BB%93%E5%90%88threadlocal%E7%9A%84%E7%94%A8%E6%B3%95%E5%AE%9E%E4%BE%8B/>Java线程池结合ThreadLocal的用法实例</a></li><li>· <a href=/blog_prepublish/%E6%8A%80%E6%9C%AF%E6%8F%90%E5%8D%87/java/object%E6%BA%90%E7%A0%81%E5%88%86%E6%9E%90/>Object源码分析</a></li><li>· <a href=/blog_prepublish/%E6%8A%80%E6%9C%AF%E6%8F%90%E5%8D%87/java/%E5%B9%B6%E5%8F%91%E7%BC%96%E7%A8%8B/threadlocal%E5%92%8Cinheritablethreadlocal%E6%BA%90%E7%A0%81%E5%88%86%E6%9E%90/>ThreadLocal和InheritableThreadLocal源码分析</a></li><li>· <a href=/blog_prepublish/%E6%8A%80%E6%9C%AF%E6%8F%90%E5%8D%87/java/java-%E5%8F%8D%E5%B0%84/>Java-反射</a></li><li>· <a href=/blog_prepublish/%E6%8A%80%E6%9C%AF%E6%8F%90%E5%8D%87/java/java8-stream/>Java8 Stream</a></li></ul></div></footer><link rel=stylesheet href=https://unpkg.com/@waline/client@v2/dist/waline.css><div id=waline></div><script type=module>
    import { init } from 'https://unpkg.com/@waline/client@v2/dist/waline.mjs';
    const locale = {
        nick: '昵称',
        nickError: '请填写昵称',
        mail: '邮箱',
        mailError: '请填写正确的邮件地址',
        link: '网址',
        optional: '可选',
        placeholder: '仅填写昵称即可发表回复。\n填写邮箱可收到回复提醒。\n评论区支持 Markdown 语法及预览。\n',
        sofa: '来发评论吧~',
        submit: '提交',
        like: '喜欢',
        cancelLike: '取消喜欢',
        reply: '回复',
        cancelReply: '取消回复',
        comment: '评论',
        refresh: '刷新',
        more: '加载更多...',
        preview: '预览',
        emoji: '表情',
        uploadImage: '上传图片',
        seconds: '秒前',
        minutes: '分钟前',
        hours: '小时前',
        days: '天前',
        now: '刚刚',
        uploading: '正在上传',
        login: '管理',
        logout: '退出',
        admin: '博主',
        sticky: '置顶',
        word: '字',
        wordHint: '评论字数应在 $0 到 $1 字之间！\n当前字数：$2',
        anonymous: '匿名',
        level0: '潜水',
        level1: '冒泡',
        level2: '吐槽',
        level3: '活跃',
        level4: '话痨',
        level5: '传说',
        gif: '表情包',
        gifSearchPlaceholder: '搜索表情包',
        profile: '个人资料',
        approved: '通过',
        waiting: '待审核',
        spam: '垃圾',
        unsticky: '取消置顶',
        oldest: '按倒序',
        latest: '按正序',
        hottest: '按热度',
        reactionTitle: '你认为这篇文章怎么样？',
    };
    init({
        
        el: '#waline',
        serverURL: 'https://blogcomments.luolin.online',
        locale,
        emoji: false,     
        search: false,    
        reaction: false,  
        requiredMeta: ['nick'],
        pageSize: 10,
        imageUploader: false,
        copyright: true,
        pageview: true,
        like: false,
    });
</script></article></main><footer class=footer><span>&copy; 2025 <a href=https://luolin1024.github.io>luolin1024</a></span> ·
<span>Powered by
<a href=https://gohugo.io/ rel="noopener noreferrer" target=_blank>Hugo</a> &
        <a href=https://github.com/adityatelange/hugo-PaperMod/ rel=noopener target=_blank>PaperMod</a></span><div>本站总访问量 <span id=umami_value_site_pv></span> 次
本站总访客数 <span id=umami_value_site_uv></span> 人
当前在线访客 <span id=umami_value_active_uv></span> 人</div><a href="https://icp.gov.moe/?keyword=20248618" target=_blank>萌ICP备20248618号</a></footer><a href=#top aria-label="go to top" title="Go to Top (Alt + G)" class=top-link id=top-link accesskey=g><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 6" fill="currentcolor"><path d="M12 6H0l6-6z"/></svg></a><script>let menu=document.getElementById("menu");menu&&(menu.scrollLeft=localStorage.getItem("menu-scroll-position"),menu.onscroll=function(){localStorage.setItem("menu-scroll-position",menu.scrollLeft)}),document.querySelectorAll('a[href^="#"]').forEach(e=>{e.addEventListener("click",function(e){e.preventDefault();var t=this.getAttribute("href").substr(1);window.matchMedia("(prefers-reduced-motion: reduce)").matches?document.querySelector(`[id='${decodeURIComponent(t)}']`).scrollIntoView():document.querySelector(`[id='${decodeURIComponent(t)}']`).scrollIntoView({behavior:"smooth"}),t==="top"?history.replaceState(null,null," "):history.pushState(null,null,`#${t}`)})})</script><script>var mybutton=document.getElementById("top-link");window.onscroll=function(){document.body.scrollTop>800||document.documentElement.scrollTop>800?(mybutton.style.visibility="visible",mybutton.style.opacity="1"):(mybutton.style.visibility="hidden",mybutton.style.opacity="0")}</script><script>document.querySelectorAll("pre > code").forEach(e=>{const n=e.parentNode.parentNode,t=document.createElement("button");t.classList.add("copy-code"),t.innerHTML="copy";function s(){t.innerHTML="copied!",setTimeout(()=>{t.innerHTML="copy"},2e3)}t.addEventListener("click",t=>{if("clipboard"in navigator){navigator.clipboard.writeText(e.textContent),s();return}const n=document.createRange();n.selectNodeContents(e);const o=window.getSelection();o.removeAllRanges(),o.addRange(n);try{document.execCommand("copy"),s()}catch{}o.removeRange(n)}),n.classList.contains("highlight")?n.appendChild(t):n.parentNode.firstChild==n||(e.parentNode.parentNode.parentNode.parentNode.parentNode.nodeName=="TABLE"?e.parentNode.parentNode.parentNode.parentNode.parentNode.appendChild(t):e.parentNode.appendChild(t))})</script></body></html>